// dapi
export const UPDATE_NETWORKS = 'UPDATE_NETWORKS';
export const UPDATE_PENDING_CONTRACT_DETAILS = 'UPDATE_PENDING_CONTRACT_DETAILS';
export const UPDATE_COMPILED_CONTRACT = 'UPDATE_COMPILED_CONTRACT';
export const UPDATE_PENDING_CONTRACT_DEPLOY = 'UPDATE_PENDING_CONTRACT_DEPLOY';
export const UPDATE_DEPLOYED_CONTRACT = 'UPDATE_DEPLOYED_CONTRACT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const DISCONNECT = 'DISCONNECT';
export const RESET = 'RESET';
